title: Bug&Soft Official Site
description: Official webpage of Bug&Soft.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

github:
  zip_url: https://bugnsoft.github.io/Bug_and_Soft-0.5.52.zip
  binarios: https://bugnsoft.github.io/PacoGame_0.5.52_Win_x86_64
  is_user_page: false