title: Bug&Soft Official Site
description: Official webpage of Bug&Soft.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

github:
  instalador: https://bugnsoft.github.io/PacoSetup_1.0.2-release.exe
  source: https://bugnsoft.github.io/Bug_and_Soft-1.0.2.zip
  is_user_page: false