title: Bug&Soft Official Site
description: Official webpage of Bug&Soft.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

github:
  zip_url: http://example.com/download.zip
  binarios: http://example.com/download.zip
  is_user_page: false