title: Bug&Soft Official Site
description: Official webpage of Bug&Soft.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

github:
  zip_url: http://example.com/download.zip
  binarios: https://bugnsoft.github.io/PacoGame_0.5.5_Win_x86_64.zip
  is_user_page: false